title: Alex Koz.'s home page
description: >-
  Creating neat things with love and tests.
  No challenge eq. no fun.
baseurl: ""
url: ""

email: a@koz.email
twitter_username: fizzer
gitlab_username:  fzzr
github_username:  fzzr-
bitbucket_username:  fzzr
linkedin_username: akozlovskij
stackoverflow: 829264/alex-ko
stackcareers: ak
vcard: /assets/Alex.Koz.vcf
cert-ace: /assets/Alex.Koz-ACE.pdf

hire: false
ocupation: Akropolis
# ocupation: independent

owner:
  name: Alex Koz.
  fullname: Alexander Kozlovski
  avatar: https://avatars1.githubusercontent.com/u/888526?v=2&s=460
  position: Snr. Software Engineer

theme: minima
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false
  enable_coderay: false

timezone: Europe/Moscow
encoding: utf-8

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - js/
  - node_modules
  - package.json
  - build.*
