title: Alex Koz.'s home page
description: >-
  Creating neat things with love.
  No challenge eq. no fun.
baseurl: ""
url: ""

email: a@koz.email
twitter_username: fizzer
gitlab_username:  fzzr
github_username:  fzzr-
bitbucket_username:  fzzr
linkedin_username: akozlovskij
stackoverflow: 829264/alex-ko
stackcareers: ak
# # patreon: https://www.patreon.com/fzzr
vcard: /assets/Alex.Koz.vcf
cert-ace: /assets/Alex.Koz-ACE.pdf

owner:
  name: Alex Koz.
  fullname: Alexander Kozlovski
  avatar: https://avatars1.githubusercontent.com/u/888526?v=2&s=460
  position: Snr. Software Engineer

markdown: kramdown
theme: minima

timezone: Europe/Moscow
encoding: utf-8

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - lod/
  - js/

# include:
#   - js/
